controllers/MainController.php
<?php

namespace app\controllers;

use phpDocumentor\Reflection\Types\Scalar;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\helpers\FileHelper;


class MainController extends Controller
{
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],

            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                //'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function beforeAction($action)
    {
        $session = Yii::$app->session;
        $session->open();
        if ((isset($session['user'])) && (Yii::$app->controller->action->id == "login"))
        {
            return $this->redirect(["main/home"]);
        }
        else if ((isset($session['user'])) || (Yii::$app->controller->action->id == "login") || (Yii::$app->controller->action->id == "captcha"))
        {
            return parent::beforeAction($action);
        } else
        {
            return $this->redirect(["main/login"]);
        }
    }

    // ckeditor image upload
    public function actionImg_upload()
    {
        $funcNum = $_REQUEST['CKEditorFuncNum'];

        if(!empty($_FILES['upload']))
        {
            $message = "";
            if (($_FILES['upload'] == "none") OR (empty($_FILES['upload']['name'])))
            {
                $message = "لطفا تصویر را بارگذاری نمایید.";
            }
            else if ($_FILES['upload']["size"] == 0 OR $_FILES['upload']["size"] > 5*1024*1024)
            {
                $message = "حجم تصویر نمی تواند از ۵ مگابایت بیشتر باشد.";
            }
            else if ( ($_FILES['upload']["type"] != "image/jpg")
                AND ($_FILES['upload']["type"] != "image/jpeg")
                AND ($_FILES['upload']["type"] != "image/png") )
            {
                $message = "فرمت تصویر معتبر نیست";
            }
            else if (!is_uploaded_file($_FILES['upload']["tmp_name"]))
            {

                $message = "بارگذاری تصویر با خطا مواجه شد";
            }
            else
            {
                $extension = pathinfo($_FILES['upload']['name'], PATHINFO_EXTENSION);
                $name = time().'.'.$extension;
                // Here is the folder where you will save the images
                $bp = \getcwd();
                $folder = '/web/images/uploads/';
                $url = Yii::$app->urlManager->createAbsoluteUrl($folder.$name);

                move_uploaded_file( $_FILES['upload']['tmp_name'], $bp.$folder.$name );
            }

            echo '<script type="text/javascript">
                window.parent.CKEDITOR.tools.callFunction("'.$funcNum.'", "'.$url.'", "'.$message.'" );
                  </script>';
        }

    }

    public function actionImg_browse()
    {
        //get function num to pass it to the view (need to be called to pass data of selected file to CKEditor)
        $CKEditorFuncNum = Yii::$app->request->get('CKEditorFuncNum');

        //get list of uploaded files
        $files = FileHelper::findFiles(getcwd().'/web/images/uploads/');
        $array = [];
        foreach ($files as $file)
        {
            array_push($array, Yii::$app->request->baseUrl.'/web/images/uploads/'.basename($file));
        }

        return $this->renderAjax('browse', [
            'funcNum' => $CKEditorFuncNum,
            'files' => $array,
        ]);
    }

//

    public function actionLogin()
    {
        $model = new \app\models\PcUsers();

        if (Yii::$app->request->isPost)
        {
            if ($model->load(Yii::$app->request->post()))
            {
                $model->password = md5($model->password);
                $user = \app\models\PcUsers::find()->where(["nid" => $model->nid, "password" => $model->password, 'enabled'=>1])->asArray()->one();
                if (!empty($user))
                {
                    $session = Yii::$app->session;
                    $session->open();

                    if (isset($session['user']))
                        $session->remove("user");

                    $user['password'] = "";
                    unset($user['password']);
                    $session['user'] = $user;

                    (new \app\components\PdcpHelper)->setUserProjectSession();

                    if($user['admin'])
                    {
                        $newTicket = \app\models\PcTickets::find()->select("COUNT(*)")->where(['read'=>false])->scalar();
                        if($newTicket > 0)
                            return $this->redirect(['main/ticket_inbox']);
                    }
                    else
                    {
                        $newTicket = \app\models\PcTickets::find()->select("COUNT(*)")->where(['new_reply'=>true])->scalar();
                        if($newTicket > 0)
                            return $this->redirect(['main/ticket_inbox']);
                    }
                    return $this->redirect(['main/home']);
                }

                Yii::$app->session->setFlash('error', "نام کاربری یا رمز عبور اشتباه است");
                $model->password = NULL;
            }
        }

        $this->layout = "login";

        $flash = ""; $msg = "";$user='';
        if(Yii::$app->session->hasFlash('error'))  { $flash = "error"; $msg = Yii::$app->session->getFlash("error");}
        $session = Yii::$app->session;
        $session->open();
        if (isset($session['user'])) $user = $session['user'];
        Yii::$app->session->destroy();
        if(!empty($user))
             $session['user'] = $user;
        if(!empty($flash)) Yii::$app->session->setFlash($flash, $msg);

        return $this->render('login',['model' => $model]);
    }

    public function actionLogout()
    {
        $session = Yii::$app->session;
        $session->open();
        if (isset($session['user']))
        {
            $session->remove('user');
            
        }

	$session->destroy();
        return $this->redirect(['main/login']);
    }

    public function actionHome()
    {
        $this->layout = "main";
        $session = Yii::$app->session;
        $session->open();
        if(isset($session['user']))
        {
            $user = $session['user'];

            if($user['reset_password'] == true)
            {
                return $this->redirect(['main/reset_password']);
            }

            if($user['admin'] == 1)
                $userProjects = \app\models\PcViewUserProjects::find()->select('project_id, project, office, ts, project_weight, contract_subject, contract_company, contract_date, contract_duration')->distinct()->where(['enabled'=>1, 'project_enabled'=>true])->orderBy(['ts'=>SORT_DESC])->asArray()->all();
            else
                $userProjects = \app\models\PcViewUserProjects::find()->select('project_id, project, office, ts, project_weight, contract_subject, contract_company, contract_date, contract_duration')->distinct()->where(['user_id'=>$user['id'], 'enabled'=>1, 'project_enabled'=>true])->orderBy(['ts'=>SORT_DESC])->asArray()->all();

            $bulletin = \app\models\PcBulletin::find()->select('id,panel_color,ts,title')->orderBy(['ts'=>SORT_DESC])->limit(4)->all();

            return $this->render("home", ['userProjects'=>$userProjects, 'bulletin'=>$bulletin]);
        }
        else
            return $this->redirect(['main/login']);

    }

    public function actionNotifications()
    {
        $this->layout = "main";
        $session = Yii::$app->session;
        $session->open();
        if(isset($session['user']))
        {
            $user = $session['user'];

            $bulletin = \app\models\PcBulletin::find()->select('id,panel_color,ts,title')->orderBy(['ts'=>SORT_DESC]);
            $notiTotalCount = $bulletin->count();
            $notiPages = new Pagination(['totalCount'=>$notiTotalCount]);
            $notiPages->pageSize = 20;
            $bulletin = $bulletin->offset($notiPages->offset)->limit($notiPages->limit)->all();

            $admin = $session['user']['admin'];

            return $this->render("notifications", ['user'=>$user, 'notiPages'=>$notiPages, 'bulletin'=>$bulletin, 'admin'=>$admin]);
        }
        else
            return $this->redirect(['main/login']);

    }

//    users
    public function actionReset_password()
    {
        $this->layout = "main";
        $session = Yii::$app->session;
        $session->open();
        $user = $session['user'];

        if(Yii::$app->request->isPost)
        {
            $post = Yii::$app->request->post();
            $id = $post['id'];
            $password = md5($post['password']);
            $passwordConfirm = md5($post['passwordConfirm']);
            $cp = md5($post['cp']);
            $model = \app\models\PcUsers::findOne($user['id']);

            if(($model->password == $cp) && ($id == $model->id) )
            {
                if($password == $passwordConfirm)
                {
                    $model->passwordConfirm = $password;
                    $model->password = $password;
                    $model->reset_password = false;
                    try
                    {
                        $model->update();
                        if($user['reset_password'] == true)
                        {
                            $session->remove('user');
                            $user['reset_password'] = false;
                            $session['user'] = $user;
                        }
                        Yii::$app->session->setFlash('success', 'رمز شما با موفقیت تغییر یافت.');
                        return $this->redirect(['main/home']);
                    }
                    catch (\Exception $e){Yii::$app->session->setFlash('error', 'تغییر رمز با خطا مواجه شد.');}
                }
                else

views/main/browse.php
<?php
/* @var $this yii\web\View */
/* @var $funcNum */
$this->title = 'PDCP|Brows';

use yii\helpers\Html;
?>
<div class="container">

    <h3 style="text-align: center; ">تصاویر بارگذاری شده در سرور</h3>

    <?php if (!empty($files)): ?>
        <div class="row">
            <?php foreach ($files as $file):?>
                <div class="col-md-4 mb-2">
                    <img
                            src="<?= $file ?>"
                            class="img-thumbnail"
                            style="cursor: pointer; margin-bottom: 2rem; width:200px; height:auto;"
                            onClick="selectImage(<?= $funcNum ?>, '<?= $file ?>')"
                    />
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>
<script type="text/javascript">
    function selectImage(funcNum, url){
        window.opener.CKEDITOR.tools.callFunction(funcNum, url)
        window.close()
    }
</script>

views/main/bulletin_view.php
<?php

/* @var $this yii\web\View */
/* @var $bulletin \app\models\PcBulletin */
/* @var $admin */



$this->title = 'PDCP|Bulletin';
use yii\helpers\Html;
?>
<div class="topic-cover bg-gradient" style="width:95%; margin:10px auto;padding:10px;">
    <br />
    <!--  bulletin  -->
    <div class="box-shadow-dark" style="width: 200px; margin:10px auto; background-color: <?= $bulletin->panel_color; ?>; color:#fff; height: 50px; text-align: center; font-weight: bold; line-height: 50px; ">
        <?= \app\components\Jdf::jdate("Y/m/d", $bulletin->ts); ?>
    </div>
    <br />
    <h4 style="color: <?= $bulletin->panel_color; ?>; text-align: center; direction: rtl; margin: 10px auto;"><?= $bulletin->title; ?></h4>
    <hr style="border-top:2px solid <?= $bulletin->panel_color; ?>">
    <div style="direction: rtl; text-align: justify; padding: 10px; color:white; margin:10px auto; width: 100%; ">
        <?= $bulletin->description; ?>
    </div>
</div>

views/main/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="topic-cover bg-gradient" style="direction: ltr;">

    <h1 style="color:white;"><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger" >
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p style="direction: rtl;color:white;">
        صفحه درخواستی شما با خطا مواجه شد
    </p>
    <p style="direction: rtl;color:white;">
        اگر چنانچه فکر می کنید این خطا از سمت سرور می باشد موضوع را به ما اطلاع دهید.
    </p>

</div>

views/main/home.php
<?php

/* @var $this yii\web\View */
/* @var  $userProjects */
/* @var  $notiPages */
/* @var  $bulletin */
/* @var  $admin */

$this->title = 'PDCP|Home';
use yii\helpers\Html;
use yii\widgets\Pjax;


Yii::$app->formatter->nullDisplay = "";
$user = ['name'=>'', 'lastname'=>''];
$sessoin = Yii::$app->session;
if(isset($sessoin['user']))
    $user= $sessoin['user'];

?>

    <div class="topic-cover bg-gradient" >
        <div class="layout-wrapper">
            <div class="layout-narrow-dim-panel">
                <img style="display: block; margin: auto; width:20%;" src="<?= Yii::$app->request->baseUrl.'/web/images/alarm.png'; ?>">
                <a href="<?= Yii::$app->request->baseUrl.'/main/notifications'; ?>" class="btn btn-primary" style="display: block; margin: auto;">مشاهده همه اعلانات </a>
                <br />
                <h4 style="text-align: center; color: white;">اعلانات اخیر</h4>

                <ul style="list-style-type: none;width: 100%; direction:rtl; padding:0; margin:0;">
                    <?php foreach ($bulletin as $bull){
                        $url = Yii::$app->request->baseUrl.'/main/bulletin_view?id='.$bull['id']; ?>
                        <!--    -->
                        <li  style="width: 100%; color:white; padding-right: 5px;">
                            <a href="javascript:void(0);" onclick="myPopup('<?= $url; ?>', 'اعلان',700, 400)" style="width: 100%;direction: rtl; display: inline-block; ">
                                <i class=" fa fa-check-square" style="color:<?= $bull['panel_color']; ?>"></i>
                                <span style="font-weight: bold; color: white; line-height: 30px; text-align: right; direction: rtl;"><?= $bull['title']; ?></span>
                            </a>
                        </li>
                        <hr style="border-top:1px dotted white;" />
                        <!--    -->
                    <?php }?>
                </ul>

                <br style="clear: both;">
            </div>

            <div class="layout-wide-dim-panel">
                <img style="width: 80px; height:auto; display:block; margin:auto;" src="<?= Yii::$app->request->baseUrl.'/web/images/logo.png'; ?>">
                <h3 style="text-align: center; color:white;">پروژه های من</h3>
                <hr />
                <br />
                <!-- flex-wrap:wrap;  -->
                <div style="display: flex;flex-direction:column; align-items:center; justify-content: center; overflow: hidden; margin-bottom: 50px;">
                    <?php
                    $url = Yii::$app->request->baseUrl.'/project/index?id=';
                    if(empty($userProjects))
                    {
                        echo "<h3 style='color:#721c24; text-align: center; direction:rtl;'>پروژه ای برای شما تعریف نشده است.</h3>";
                    }
                    else
                    {
                        foreach ($userProjects as $rec)
                        {
                            echo \app\components\ProjectWidget::widget(['model' => $rec, 'url' => $url]);
                        }
                    }
                    ?>

                    <br style="clear:both;" />
                </div>
            </div>
        </div>
    </div>

views/main/login.php
<?php
/* @var $this yii\web\View */
/* @var $model */
$this->title = 'PDCP|Login';

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

?>
<div class="bg-cover login-cover">

    <div class="box-shadow-dodgerblue" style="position: absolute;min-width:350px; top: 50%;left: 50%;transform: translate(-50%, -50%); background-color: rgba(50,50,50,0.7); padding: 20px; border-radius:10px;">
        <h5 style="color:white; text-align: center; padding:5px;">مخابرات منطقه تهران</h5>

        <img src="<?= Yii::$app->request->baseUrl.'/web/images/logo.png'; ?>" style="display: block; margin:auto; width:40px;height:40px;">
        <h4 style="color:white; text-align: center; padding:15px;">سامانه جامع کنترل پروژه</h4>
        <hr style="margin:2px; padding:0px;" />
        <?php $form = ActiveForm::begin(['options' => ['style' => "width:90%; max-width:300px; margin:auto; display:block; direction:rtl;"]]); ?>

        <?= $form->field($model, 'nid', ['labelOptions' => ['style' => 'color:white;'], 'errorOptions' => ['class' => 'text-danger']])->textInput(['placeholder' => "کد ملی خود را وارد نمایید"]); ?>
        <?= $form->field($model, 'password', ['labelOptions' => ['style' => 'color:white;'], 'errorOptions' => ['class' => 'text-danger']])->passwordInput(['placeholder' => "رمز عبور خود را وارد نمایید"]); ?>
        
        <?= $form->field($model, 'verifyCode', ['options'=>['style'=>'margin:0px;direction:rtl;'], 'labelOptions'=>['style'=>"padding:0; margin:0;width:100%;text-align:right; color:white; height:40px; line-height:40px;"]])
                ->widget(Captcha::className(), 
                [
                'options'=>['class'=>"form-control enFont text-right", 'style'=>'height:100%; width:100%;'],
                'template' => '  <div style="height:100%; width:100%; padding:0;">
                                        <div class="row" style="width:100%; padding:0; margin:0;">
                                        <div class="col-md-5" style="padding:0; margin:0;height:40px;">{image}</div>
                                        <div class="col-md-7" style="padding:0; margin:0;height:40px;">{input}</div>
                                         </div>
                                      </div>
                               ',
            ]); ?>

        <div class="form-group" style="width:100px;margin:auto;">
            <br />
            <button type="submit" style="min-width:120px;" class="btn btn-success"><i class="fa fa-sign-in-alt text-white"></i> ورود</button>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
    <!-- display error message -->
    <?php if (Yii::$app->session->hasFlash('error')): ?>
        <div  class="alert alert-danger alert-dismissible fade in" align="center" style="text-align: right; direction:rtl; margin: auto;">
<!--            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>-->
            <?= Yii::$app->session->getFlash('error') ?>
        </div>
        <br/>
    <?php endif; ?>
</div>

views/main/logs.php
<?php

/* @var $this yii\web\View */
/* @var  $dProvider */
/* @var  $sModel */
/* @var  $project */

$this->title = 'pControl|logs';
use yii\helpers\Html;
use yii\grid\GridView;
Yii::$app->formatter->nullDisplay = "";
?>

<i class="fa fa-history fa-2x text-primary" style="display: block; text-align:center; margin:auto;" ></i>
<h3 style="text-align: center;color:mediumvioletred;">تاریخچه تغییرات</h3>
<hr style="border:1px solid lightgray;" />

<div id="historycontainer" style="overflow:auto; direction:rtl; height: 100%; font-size: 14px;">
    <i class="fa fa-arrow-right" style="position: fixed; right:0px; color:mediumvioletred; cursor: pointer;" onclick="scRight()" ></i>
    <i class="fa fa-arrow-left" style="position:fixed; left:0px; color:mediumvioletred; cursor: pointer;" onclick="scLeft()"></i>

    <?= GridView::widget([
        'tableOptions'=>['id'=>"users-Table", 'class'=>'table table-striped table-bordered table-hover text-center'],
        //'headerRowOptions'=>['class'=>'bg-info text-center'],
        'rowOptions' =>function ($model, $key, $index, $grid) {return ['id'=>'row'.$model['id'], 'rec-id'=>$model['id'], 'class'=>'table_row', 'onclick'=>'activateRow(this.getAttribute("id"));'];},
        'dataProvider' => $dProvider,
        'filterModel' => $sModel,
        'filterRowOptions' =>['style'=>"direction:ltr"],
        'summary' => 'نمایش <b>{begin} تا {end}</b> از <b>{totalCount}</b> ',
        'layout' => "{summary}\n{items}\n<div align='center' >{pager}</div>",
        'columns' => [

            [
                'attribute' =>'name',
                'headerOptions' => ['class' => 'bg-info text-center'],
                'contentOptions' => ['class' => 'text-center', 'style'=>"vertical-align: middle;min-width:50px;", 'title'=>'نام'],
            ],
            //3
            [
                'attribute' =>'lastname',
                'headerOptions' => ['class' => 'bg-info text-center'],
                'contentOptions' => ['class' => 'text-center', 'style'=>"vertical-align: middle;min-width:80px;", 'title'=>'نام خانوادگی'],
            ],
            [
                'attribute' =>'office',
                'headerOptions' => ['class' => 'bg-info text-center'],
                'contentOptions' => ['class' => 'text-center', 'style'=>"vertical-align: middle;min-width:80px;", 'title'=>'اداره کل '],
            ],
            [
                'attribute' =>'post',
                'headerOptions' => ['class' => 'bg-info text-center'],
                'contentOptions' => ['class' => 'text-center', 'style'=>"vertical-align: middle;min-width:80px;", 'title'=>'سمت'],
            ],
            [
                'attribute' =>'area',
                'headerOptions' => ['class' => 'bg-info text-center'],
                'contentOptions' => ['class' => 'text-center', 'style'=>"vertical-align: middle;min-width:80px;", 'title'=>'منطقه'],
            ],
            [
                'attribute' =>'exchange',
                'headerOptions' => ['class' => 'bg-info text-center'],
                'contentOptions' => ['class' => 'text-center', 'style'=>"vertical-align: middle;min-width:80px;", 'title'=>'مرکز '],
            ],
            [
                'attribute' =>'site_id',
                'headerOptions' => ['class' => 'bg-info text-center'],
                'contentOptions' => ['class' => 'text-center', 'style'=>"vertical-align: middle;min-width:80px;", 'title'=>'شناسه سایت '],
            ],
            [
                'attribute' =>'kv_code',
                'headerOptions' => ['class' => 'bg-info text-center'],
                'contentOptions' => ['class' => 'text-center', 'style'=>"vertical-align: middle;min-width:80px;", 'title'=>'کد کافو'],
            ],
            [
                'attribute' =>'action',
                'headerOptions' => ['class' => 'bg-info text-center'],
                'contentOptions' => ['class' => 'text-center', 'style'=>"vertical-align: middle;min-width:80px;", 'title'=>'عملیات '],
            ],
            [
                'attribute' =>'ts',
                'headerOptions' => ['class' => 'bg-info text-center'],
                'contentOptions' => ['class' => 'text-center', 'style'=>"vertical-align: middle;min-width:80px;", 'title'=>'زمان '],
                'format'=>'html',
                'value'=>function($data){return \app\components\Jdf::jdate("Y/m/d h:i", $data['ts']);}
            ],
            [
                'attribute' =>'project',
                'headerOptions' => ['class' => 'bg-info text-center'],
                'contentOptions' => ['class' => 'text-center', 'style'=>"vertical-align: middle;min-width:80px;", 'title'=>'پروژه '],
            ],

        ],

    ]);

    ?>

</div>




<?php
$bPath = Yii::$app->request->baseUrl ;
$script =<<< JS

function activateRow(rowId)
{
$(".selectedRow").removeClass("selectedRow");
$("#"+rowId).addClass("selectedRow");
}

function scRight()
{
    $("#gwcontainer").animate({scrollLeft: "+=800px"}, "slow");
}

function scLeft()
{
    $("#gwcontainer").animate({scrollLeft: "-=800px"}, "slow");
}

JS;
$this->registerJs($script, Yii\web\View::POS_END);
?>
<br />

views/main/notification_new.php
<?php

/* @var $this yii\web\View */
/* @var $model */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use dosamigos\ckeditor\CKEditor;

$this->title = 'PDCP|New notification';
?>
<p class="backicon">
    <a href="notifications"><i class="fa fa-chevron-left fa-2x" style="color:white;position: relative;"></i></a>
</p>
<div class="topic-cover bg-gradient">
<div class="row" style="width:100%;  max-width:1000px; margin:auto;">
    <div class="col-md-9">
        <div style="margin:auto; padding: 20px;" >
            <h4 class="text-center" style="direction: rtl;color:white;">برای ایجاد اعلان جدید فرم زیر را تکمیل نمایید.</h4>
            <?php
            $form = ActiveForm::begin([
                'id'=>"notiForm",
                'options'=>['style'=>'direction:rtl; width:90%; max-width:600px;min-width:100px; margin:auto']
            ]); ?>

            <?= $form->field($model, 'panel_color', ['options'=>['style'=>''],'labelOptions'=>['style'=>'color:white;']])->dropDownList([ 'olivedrab'=>'سبز', 'mediumvioletred'=>'قرمز', 'dodgerblue'=>'آبی'] ); ?>
            <?= $form->field($model, 'title', ['options'=>['style'=>''],'labelOptions'=>['style'=>'color:white;']])->textInput(['maxlength' => true, 'style'=>"direction:rtl", 'placeholder' => "تیتر"]) ?>
            <?= $form->field($model, 'description')->widget(CKEditor::className(), ['options' => ['id'=>'ticket' ,'rows' => 10, 'required'=>true], 'preset' => 'full',
                'clientOptions' => ['language' => 'fa',
                    'allowedContent' => true,
                    'filebrowserUploadUrl' => yii\helpers\Url::to(['/main/img_upload']),
                    'filebrowserBrowseUrl' => Yii::$app->request->baseUrl.'/main/img_browse',
                ] ]) ?>

            <div class="form-group">
                <br/>
                <br/>
                <?= Html::submitButton('تایید', ['class' => 'btn btn-success pull-left']) ?>

            </div>
            <br/>
            <br/>
            <?php ActiveForm::end(); ?>

        </div>
    </div>
    <div class="col-md-3">
        <img src="<?= Yii::$app->request->baseUrl.'/web/images/alarm.png'; ?>" style="display: block;width:90%; max-width:200px;height:auto;padding-top: 45%; margin:auto;">
    </div>
</div>
<br/>
</div>

views/main/notification_remove.php
<?php

/* @var $this yii\web\View */
/* @var $model $model */
$this->title = 'PDCP|Remove Notification';
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;


Yii::$app->formatter->nullDisplay = "";
?>
<p class="backicon">
    <a href="notifications"><i class="fa fa-chevron-left fa-2x" style="color:white;position: relative;"></i></a>
</p>
<div class="topic-cover bg-gradient">

<div class="record-remove" style="direction:rtl;">
    <h3 class="text-center" style="color:white;">حذف اعلان</h3>
    <br />
<?php
    $form = ActiveForm::begin([
    'id'=>"recForm",
    'options'=>['style'=>'direction:rtl;max-width:400px;min-width:100px; margin:auto','onsubmit' => "return confirm('آیا از حذف اعلان اطمینان دارید؟');"]
    ]); ?>

    <div class="form-group">
        <?= $form->field($model, 'id')->hiddenInput()->label(false); ?>
        <?= Html::submitButton('<i style="color:red;" class="fa fa-trash  fa-3x" title="حذف اعلان"></i>', ['class'=>'hvr-bounce-in', 'style' =>'display:block; margin:auto;border:none; background:transparent;']) ?>
    </div>
    <br/>
    <?php ActiveForm::end(); ?>

    <!--  bulletin  -->
    <div class="box-shadow-dark" style="width: 200px; margin:10px auto; background-color: <?= $model->panel_color; ?>; color:#fff; height: 50px; text-align: center; font-weight: bold; line-height: 50px; ">
        <?= \app\components\Jdf::jdate("Y/m/d", $model->ts); ?>
    </div>
    <br />
    <h4 style="color: <?= $model->panel_color; ?>; text-align: center; direction: rtl; margin: 10px auto;"><?= $model->title; ?></h4>
    <hr style="border-top:2px solid <?= $model->panel_color; ?>">
    <div style="direction: rtl; text-align: justify;color:white; padding: 10px; margin:10px auto; width: 100%; ">
        <?= $model->description; ?>
    </div>



</div>
<br />
</div>

views/main/projects.php
<?php

/* @var $this yii\web\View */
/* @var  $model */

$this->title = 'pControl|Home';
use yii\helpers\Html;
Yii::$app->formatter->nullDisplay = "";
?>

<i class="fas fa-project-diagram fa-2x text-primary" style="display: block; text-align:center; margin:auto;" ></i>
<h3 style="text-align: center;">مدیریت پروژه ها </h3>

<hr style="border:1px solid lightgray;" />
<div style="display: flex; align-items:center; flex-wrap:wrap; justify-content: center;">
    <?php
        foreach ($model as $rec)
        {
//            echo \app\components\ProjectWidget::widget(['model'=>$rec]);
        }

    ?>
</div>
<br />